"use client";

import LactoNavigation from "@/app/template-components/lacto/lacto-navigation";
import HeaderTitle from "@/app/template-components/header/header-title";
import HeaderTitleButton from "@/app/template-components/header/header-title-button";
import HeaderTitleDescription from "@/app/template-components/header/header-title-description";
import HeaderTitleDescriptionButton from "@/app/template-components/header/header-title-description-button";
import TerraFeaturesImageLeft from "@/app/template-components/terra/terra-features-image-left";
import TerraFeaturesImageRight from "@/app/template-components/terra/terra-features-image-right";

export default function StagingPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between">
      <LactoNavigation thumbnail="/images/thumbnails/placeholder.svg" images={[{"label":"Logo","propId":"logoId","suffix":"logo"}]} links={[{"label":"Menu 1","propId":"menu1Id","suffix":"menu-1","labelProp":"menu1Label","visibleProp":"menu1Visible","linkTypeProp":"menu1LinkType"},{"label":"Menu 2","propId":"menu2Id","suffix":"menu-2","labelProp":"menu2Label","visibleProp":"menu2Visible","linkTypeProp":"menu2LinkType"},{"label":"Menu 3","propId":"menu3Id","suffix":"menu-3","labelProp":"menu3Label","visibleProp":"menu3Visible","linkTypeProp":"menu3LinkType"},{"label":"Menu 4","propId":"menu4Id","suffix":"menu-4","labelProp":"menu4Label","visibleProp":"menu4Visible","linkTypeProp":"menu4LinkType"}]} props={{"menu1Label":"Menu 1","menu1Url":"","menu2Label":"Menu 2","menu2Url":"","menu3Label":"Menu 3","menu3Url":"","menu4Label":"Menu 4","menu4Url":""}} component={undefined} menu1Label="Menu 1" menu1Url="" menu2Label="Menu 2" menu2Url="" menu3Label="Menu 3" menu3Url="" menu4Label="Menu 4" menu4Url="" sectionId="navigation-9763" />
      <HeaderTitle thumbnail="/images/thumbnails/header-title.svg" props={{}} component={undefined} sectionId="header-5332" />
      <HeaderTitleButton thumbnail="/images/thumbnails/header-title-button.svg" buttons={[{"label":"Button","propId":"buttonId","suffix":"button","labelProp":"buttonText","visibleProp":"buttonVisible","linkTypeProp":"buttonLinkType"},{"label":"Secondary Button","propId":"secondaryButtonId","suffix":"secondary-button","labelProp":"secondaryButtonText","visibleProp":"secondaryButtonVisible","linkTypeProp":"secondaryButtonLinkType"}]} props={{"buttonStyle":"primary","buttonLinkType":"url","secondaryButtonLinkType":"url","buttonText":"Label","secondaryButtonText":"Label"}} component={undefined} buttonStyle="primary" buttonLinkType="url" secondaryButtonLinkType="url" buttonText="Label" secondaryButtonText="Label" sectionId="header-5352" />
      <HeaderTitleDescription thumbnail="/images/thumbnails/header-title-desc.svg" props={{}} component={undefined} sectionId="header-5714" />
      <HeaderTitleDescriptionButton thumbnail="/images/thumbnails/header-title-desc-button.svg" buttons={[{"label":"Button","propId":"buttonId","suffix":"button","labelProp":"buttonText","visibleProp":"buttonVisible","linkTypeProp":"buttonLinkType"},{"label":"Secondary Button","propId":"secondaryButtonId","suffix":"secondary-button","labelProp":"secondaryButtonText","visibleProp":"secondaryButtonVisible","linkTypeProp":"secondaryButtonLinkType"}]} props={{"buttonStyle":"primary","buttonLinkType":"url","secondaryButtonLinkType":"url","buttonText":"Label","secondaryButtonText":"Label"}} component={undefined} buttonStyle="primary" buttonLinkType="url" secondaryButtonLinkType="url" buttonText="Label" secondaryButtonText="Label" sectionId="header-5482" />
      <TerraFeaturesImageLeft thumbnail="/images/thumbnails/terra-image-left.svg" buttons={[{"label":"Button","propId":"buttonId","suffix":"button","labelProp":"buttonText","visibleProp":"buttonVisible","linkTypeProp":"buttonLinkType"},{"label":"Secondary Button","propId":"secondaryButtonId","suffix":"secondary-button","labelProp":"secondaryButtonText","visibleProp":"secondaryButtonVisible","linkTypeProp":"secondaryButtonLinkType"}]} images={[{"label":"Image","propId":"imageId","suffix":"image","visibleProp":"imageVisible"}]} props={{"buttonStyle":"primary","buttonLinkType":"url","secondaryButtonLinkType":"url","secondaryButtonText":"Label"}} component={undefined} buttonStyle="primary" buttonLinkType="url" secondaryButtonLinkType="url" secondaryButtonText="Label" sectionId="feature-split-8236" />
      <TerraFeaturesImageRight thumbnail="/images/thumbnails/terra-image-right.svg" buttons={[{"label":"Button","propId":"buttonId","suffix":"button","labelProp":"buttonText","visibleProp":"buttonVisible","linkTypeProp":"buttonLinkType"}]} images={[{"label":"Image","propId":"imageId","suffix":"image","visibleProp":"imageVisible"}]} props={{"buttonStyle":"primary"}} component={undefined} buttonStyle="primary" sectionId="feature-split-2644" />
    </main>
  );
}
